default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
        args: [./...]
      - id: go-mod-tidy
      - id: go-lint # requires golang.org/x/lint/golint
      - id: go-imports # requires golang.org/x/tools/cmd/goimports
      - id: go-cyclo # requires github.com/fzipp/gocyclo/cmd/gocyclo
        args: [-over=15]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
